
import os
from dotenv import load_dotenv
import backtrader as bt
import pandas as pd
import json
from datetime import datetime, timedelta
import argparse


# --- Adaptive Pullback Momentum v1.1 Strategy (Shorts Only) ---

class APMv1Strategy(bt.Strategy):
    params = dict(
        ema_fast=21,
        ema_mid=50,
        ema_slow=200,
        adx_thresh=15,
        adx_len=14,
        pb_pct=0.004,  # 0.40% pullback tolerance
        mom_bars=5,
        rsi_len=14,
                rsi_lo=30,
                rsi_hi=58,
                vol_len=20,
                vol_mult=0.3,
                min_body=0.15,
                atr_len=14,
                atr_bl_len=60,
                atr_floor=0.001,
                panic_mult=1.5,
                sess_on=True,
                sess_start=9,
                sess_end=14,
                sl_mult=4.0,
                tp_mult=8.0,
                tr_act=3.5,
                tr_dist=0.1,
                risk_pct=0.02,
                max_bars=0
    )

    def __init__(self):
        self.ema_fast = bt.ind.EMA(period=self.p.ema_fast)
        self.ema_mid = bt.ind.EMA(period=self.p.ema_mid)
        self.ema_slow = bt.ind.EMA(period=self.p.ema_slow)
        self.adx = bt.ind.ADX(period=self.p.adx_len)
        self.rsi = bt.ind.RSI(period=self.p.rsi_len)
        self.atr = bt.ind.ATR(period=self.p.atr_len)
        self.atr_bl = bt.ind.SMA(self.atr, period=self.p.atr_bl_len)
        self.vol_ma = bt.ind.SMA(self.data.volume, period=self.p.vol_len)
        self.trades = []
        self.equity_curve = []
        self.sl = None
        self.tp = None
        self.trail_active = False
        # All trading logic moved to next()



if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Backtest strategies")
    parser.add_argument("--symbol", type=str, default="BTC-USD", help="Symbol (use BTC-USD for yfinance)")
    parser.add_argument("--strategy", type=str, default="apm", choices=["apm", "APMv1Strategy"], help="Strategy")
    parser.add_argument("--cash", type=float, default=10000, help="Starting cash")
    args = parser.parse_args()

    # Load BTCUSD 5m YTD data from CSV (generated by fetch_alpaca_btcusd_5m_ytd.py)
    csv_path = "backend/data/btc_usd_5m_ytd.csv"
    if not os.path.exists(csv_path):
        print(f"[ERROR] Data file not found: {csv_path}\nRun fetch_alpaca_btcusd_5m_ytd.py first.")
        exit(1)
    df = pd.read_csv(csv_path, parse_dates=True, index_col=0)
    df.dropna(inplace=True)
    if df.empty:
        print(f"[ERROR] No data in {csv_path}.")
        exit(1)
    # Backtrader expects columns: open, high, low, close, volume, datetime (index)
    data = bt.feeds.PandasData(dataname=df)
    cerebro = bt.Cerebro()
    # Select strategy based on CLI argument
    if args.strategy.lower() in ["apm", "apmv1strategy"]:
        cerebro.addstrategy(APMv1Strategy)
    else:
        raise ValueError(f"Unknown strategy: {args.strategy}")
    cerebro.adddata(data)
    cerebro.broker.setcash(args.cash)
    results = cerebro.run()
    strat = results[0]

    trades = getattr(strat, 'trades', [])
    equity_curve = getattr(strat, 'equity_curve', [])
    total_trades = len(trades)
    wins = sum(1 for t in trades if t.get('won'))
    losses = total_trades - wins
    win_rate = (wins / total_trades * 100) if total_trades else 0
    start_val = equity_curve[0] if equity_curve else args.cash
    end_val = equity_curve[-1] if equity_curve else cerebro.broker.getvalue()
    net_return = ((end_val - start_val) / start_val * 100) if start_val else 0
    peak = equity_curve[0] if equity_curve else start_val
    max_dd = 0
    for v in equity_curve:
        if v > peak:
            peak = v
        dd = (peak - v) / peak if peak else 0
        if dd > max_dd:
            max_dd = dd
    max_dd_pct = max_dd * 100

    print(f"\n--- Backtest Results for {args.symbol} (APMv1Strategy) ---")
    print(f"Trades: {total_trades} | Wins: {wins} | Losses: {losses}")
    print(f"Win rate: {win_rate:.2f}%")
    print(f"Net return: {net_return:.2f}%")
    print(f"Max drawdown: {max_dd_pct:.2f}%")
    print(f"Final Portfolio Value: {end_val:.2f}")

    def __init__(self):
        self.ema_fast = bt.ind.EMA(period=self.p.ema_fast)
        self.ema_mid = bt.ind.EMA(period=self.p.ema_mid)
        self.ema_slow = bt.ind.EMA(period=self.p.ema_slow)
        self.adx = bt.ind.ADX(period=self.p.adx_len)
        self.rsi = bt.ind.RSI(period=self.p.rsi_len)
        self.atr = bt.ind.ATR(period=self.p.atr_len)
        self.atr_bl = bt.ind.SMA(self.atr, period=self.p.atr_bl_len)
        self.vol_ma = bt.ind.SMA(self.data.volume, period=self.p.vol_len)
        self.trades = []
        self.equity_curve = []
        self.sl = None
        self.tp = None
        self.trail_active = False
        self.best = None
        self.bar_in_trade = 0

    def notify_trade(self, trade):
        if trade.isclosed:
            result = {
                'won': trade.pnl > 0,
                'pnl': trade.pnl,
                'size': trade.size,
                'price': trade.price,
                'barclose': self.datas[0].datetime.datetime(0)
            }
            self.trades.append(result)

    def next(self):
        pos = self.position
        close = self.datas[0].close[0]
        high = self.datas[0].high[0]
        low = self.datas[0].low[0]
        open_ = self.datas[0].open[0]
        volume = self.datas[0].volume[0]
        equity = self.broker.getvalue()
        self.equity_curve.append(equity)
        self.bar_in_trade = self.bar_in_trade + 1 if pos else 0

        # --- Entry Filters (Shorts Only) ---
        # Ensure enough bars for all lookbacks
        min_bars = max(
            2,  # for ema_fast[-2]
            self.p.mom_bars if self.p.mom_bars > 0 else 0,
            1  # for high[-1], ema_fast[-1]
        )
        if len(self) < min_bars:
            print(f"[DEBUG] Not enough bars: {len(self)} < {min_bars}")
            return
        # EMA stack: fast < mid < slow
        if not (self.ema_fast[0] < self.ema_mid[0] < self.ema_slow[0]):
            print(f"[DEBUG] EMA stack failed: {self.ema_fast[0]:.2f}, {self.ema_mid[0]:.2f}, {self.ema_slow[0]:.2f}")
            return
        # EMA21 falling over 3 bars
        if not (self.ema_fast[0] < self.ema_fast[-1] < self.ema_fast[-2]):
            print(f"[DEBUG] EMA21 falling failed: {self.ema_fast[0]:.2f}, {self.ema_fast[-1]:.2f}, {self.ema_fast[-2]:.2f}")
            return
        # ADX > threshold
        if self.adx[0] < self.p.adx_thresh:
            print(f"[DEBUG] ADX filter failed: {self.adx[0]:.2f} < {self.p.adx_thresh}")
            return
        # RSI falling and in range
        if not (self.rsi[0] < self.rsi[-1] and self.p.rsi_lo <= self.rsi[0] <= self.p.rsi_hi):
            print(f"[DEBUG] RSI filter failed: {self.rsi[0]:.2f}, {self.rsi[-1]:.2f}, range=({self.p.rsi_lo},{self.p.rsi_hi})")
            return
        # Momentum: close < close[mom_bars]
        if self.p.mom_bars > 0 and len(self.data.close) > self.p.mom_bars and close >= self.data.close[-self.p.mom_bars]:
            print(f"[DEBUG] Momentum filter failed: close={close:.2f} >= close[-{self.p.mom_bars}]={self.data.close[-self.p.mom_bars]:.2f}")
            return
        # Prev bar high tags EMA21 zone (±pb_pct)
        prev_high = self.data.high[-1]
        prev_ema = self.ema_fast[-1]
        if abs(prev_high - prev_ema) > self.p.pb_pct * prev_ema:
            print(f"[DEBUG] Prev high/EMA21 filter failed: |{prev_high:.2f} - {prev_ema:.2f}| > {self.p.pb_pct * prev_ema:.2f}")
            return
        # Current bar closes below EMA21 with body
        if not (close < self.ema_fast[0] and abs(close - open_) > self.p.min_body * self.atr[0]):
            print(f"[DEBUG] Close/body filter failed: close={close:.2f}, open={open_:.2f}, ema21={self.ema_fast[0]:.2f}, min_body={self.p.min_body * self.atr[0]:.2f}")
            return
        # Volume filter
        if volume < self.p.vol_mult * self.vol_ma[0]:
            print(f"[DEBUG] Volume filter failed: volume={volume:.2f} < {self.p.vol_mult * self.vol_ma[0]:.2f}")
            return
        # ATR floor
        if self.atr[0] / close < self.p.atr_floor:
            print(f"[DEBUG] ATR floor filter failed: atr/close={self.atr[0]/close:.4f} < {self.p.atr_floor}")
            return
        # Session filter (09:00–14:00 ET)
        if self.p.sess_on:
            bar_hour = self.datas[0].datetime.datetime(0).hour
            if not (self.p.sess_start <= bar_hour < self.p.sess_end):
                print(f"[DEBUG] Session filter failed: hour={bar_hour}")
                return
        # Panic filter
        if self.atr[0] > self.p.panic_mult * self.atr_bl[0]:
            print(f"[DEBUG] Panic filter failed: atr={self.atr[0]:.2f} > {self.p.panic_mult * self.atr_bl[0]:.2f}")
            return

            # --- Position Sizing ---
            stop_dist = self.p.sl_mult * self.atr[0]
            risk_qty = equity * self.p.risk_pct / stop_dist if stop_dist > 0 else 0
            entry_qty = risk_qty

            # --- Entry (Short Only) ---
            if not pos and entry_qty > 0:
                self.sell(size=entry_qty)
                self.sl = close + stop_dist
                self.tp = close - self.p.tp_mult * self.atr[0]
                self.best = close
                self.trail_active = False
                self.bar_in_trade = 0
                return

            # --- Exit Management ---
            if pos:
                self.best = min(self.best, low) if self.best is not None else low
                # Trail activation
                if not self.trail_active and (pos.price - low) >= self.p.tr_act * self.atr[0]:
                    self.trail_active = True
                # Trailing stop
                if self.trail_active:
                    trail_sl = self.best + self.p.tr_dist * self.atr[0]
                    self.sl = min(self.sl, trail_sl)
                # Hard SL/TP
                if high >= self.sl:
                    self.close()
                elif low <= self.tp:
                    self.close()
                # Max bars in trade
                if self.p.max_bars > 0 and self.bar_in_trade >= self.p.max_bars:
                    self.close()

class SmaCrossoverStrategy(bt.Strategy):
        # ...existing code...
    params = dict(
        fast=10,
        slow=30,
        risk_pct=0.02,
        lev_cap=3.0,
        atr_period=14,
        atr_mult_sl=1.5,
        atr_mult_tp=3.0
    )


